apply plugin: 'com.android.application'

android {
    namespace 'net.sourceforge.opencamera'
    compileSdkVersion 36
    buildToolsVersion "37.0.0"
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    compileOptions.encoding = 'UTF-8'

    defaultConfig {
        applicationId "lostmsu.opencamera.app"
        minSdkVersion 21
        // Important! When we decide to change this to 30 or more, we need to add full support for scoped storage
        //noinspection ExpiredTargetSdkVersion
        targetSdkVersion 29

        testApplicationId "lostmsu.opencamera.app.test"
        testInstrumentationRunner "android.test.InstrumentationTestRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
            signingConfig signingConfigs.debug
        }
    }


    testOptions {
        unitTests.returnDefaultValues = true
        unitTests.all {
            testLogging {
                outputs.upToDateWhen {false}
                exceptionFormat "full"
                events "skipped", "passed", "failed"
                showStandardStreams true
            }
        }
    }
    // needed to use android.test package (ActivityInstrumentationTestCase2 etc) when targetting sdk 28 (Android 9) -
    // see https://developer.android.com/training/testing/set-up-project
    useLibrary 'android.test.runner'
    useLibrary 'android.test.base'
    lint {
        abortOnError false
        checkReleaseBuilds false
    }
    //useLibrary 'android.test.mock'
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.exifinterface:exifinterface:1.4.2'
}
